### ISSUE TITLE
Cannot opt into compiled release after uncompiled release is uploaded

### ISSUE THREAD

**Issue by krishicks** [cloudfoundry/cf-deployment#123]
Hi,

We ran into an issue where we were deploying cf-deployment onto bosh-lite *without* using compiled releases (which is presently just mysql). We later switched to using the use-compiled-releases opsfile, but found it wasn't being utilized; bosh skipped uploading the compiled release and compiled the release anyway.

We spoke with @anEXPer who believed it would work if the uncompiled release was deleted prior to deploying with the compiled release, or perhaps stripping the version attribute from the compiled release in the list of releases in the rendered manifest.

We weren't able to test either of these as compilation succeeded the second time around.

Cheers,

KH && @aashah

**Comment by dsabeti** [comment]
Hey @krishicks. Thanks for bringing this up. My reading of this is that, if an uncompiled release is uploaded to a director first, and a compiled release is uploaded second, then a deploy -- even with an ops file that asks for a compiled release -- will use the uncompiled release and begin compilation. Do I understand that correctly?

Also, are you using the bosh-lite ops-file (`operations/bosh-lite.yml`) provided by cf-deployment? As is, that ops-file uses postgres instead of mysql release, so you might find that using `operations/use-compiled-releases.yml` doesn't help you.

**Comment by krishicks** [comment]
> My reading of this is that, if an uncompiled release is uploaded to a director first, and a compiled release is uploaded second, then a deploy -- even with an ops file that asks for a compiled release -- will use the uncompiled release and begin compilation.

That's correct.

And yes, we are using `operations/bosh-lite.yml`, but we've massaged it and `cf-deployment.yml` to allow for deploying both mysql and postgresql, and have added another ops file to allow switching properties to use one or the other.

**Comment by dsabeti** [comment]
Yup, I successfully reproduced the issue: https://gist.github.com/dsabeti/c7fd3d36f9b06e6df62cbdb599d0e475

@cppforlife, does it make sense to change this behavior in the director? If so, maybe RelInt could pair with someone from BOSH.

**Comment by dsabeti** [comment]
Hey @krishicks. I spoke with @cppforlife and it looks like this is desired behavior in the BOSH director, so I'm not sure if there's anything we can do about it on the cf-deployment side. If you have other concerns or questions about this, I'd suggest following up the BOSH team directly.

**Comment by krishicks** [comment]
Meh.
