### ISSUE TITLE
Create Service Broker Error - certificate verify failed

### ISSUE THREAD

**Issue by amitoj** [cloudfoundry/cf-deployment#136]
Hi,
Deploying service broker on cf-deployment, based on this [Stark & Wayne blog](http://www.starkandwayne.com/blog/register-your-own-service-broker-with-any-cloud-foundry/), throws following error message -

` cf create-service-broker haash-broker warreng natedogg https://${broker_url} --space-scoped`

> Server error, status code: 500, error code: 10001, message: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed

I've successfully created the service broker on PCFDev, so I must be missing something while following the same procedure on cf-deployment.

**Comment by dsabeti** [comment]
Hey @amitoj, happy to help. Could you start by providing your manifest **with credentials redacted**. If you're using and ops-files with your deploy command, could you provide those as well?

**Comment by amitoj** [comment]
Hi @dsabeti,

My bosh-lite cf-deployment environment is based on files from
https://github.com/cloudfoundry/bosh-deployment 
https://github.com/cloudfoundry/cf-deployment

Bosh-lite bootstrap using,

```
bosh create-env bosh.yml \  
  --state ./state.json \
  -o virtualbox/cpi.yml \
  -o virtualbox/outbound-network.yml \
  -o bosh-lite.yml \
  -o bosh-lite-runc.yml \
  -o jumpbox-user.yml \
  --vars-store ./creds.yml \
  -v director_name="Bosh Lite Director" \
  -v internal_ip=192.168.50.6 \
  -v internal_gw=192.168.50.1 \
  -v internal_cidr=192.168.50.0/24 \
  -v outbound_network_name=NatNetwork
```

And after initial cf-deployment cloud-config setup, 

```
bosh -e vbox -d cf deploy cf-deployment.yml \  
  -o operations/bosh-lite.yml \
  --vars-store deployment-vars.yml \
  -v system_domain=bosh-lite.com
```

CF cli login using,

```
cf api https://api.bosh-lite.com --skip-ssl-validation  
export CF_ADMIN_PASSWORD=$(bosh int ./deployment-vars.yml --path /uaa_scim_users_admin_password)  
cf auth admin $CF_ADMIN_PASSWORD
```

After this I'm followed the steps from the S&W blog to register the service broker.
1. cf create-space demo-broker (works)
2. github clone project and gradle assemble (works)
3. cf push app (works)
4. cf create-space demo-apps (works)
5. cf create-service-broker haash-broker ....  (fails)


Let me know if you need further info.
Thanks.

**Comment by dsabeti** [comment]
Hey @amitoj.

After digging into this, I think I understand what's happening. The basic problem is that cf-deployment doesn't have complete support for using TLS for all communication paths yet. Our testing for `cf create-service-broker` uses http (rather than https) for this workflow, so that's how we've missed this. (I can go into more detail about this issue if you're interested.)

I've create a [placeholder story to try to address the issue](https://www.pivotaltracker.com/story/show/144260291). I'm going to bring this to the engineering team to discuss potential fixes for this.

In the meantime, as a workaround, you should consider using `http` instead of `https` as the scheme for your broker url:
```
cf create-service-broker ... http://${broker_url} ...
```

Let me know if that helps.

**Comment by amitoj** [comment]
Thanks @dsabeti 
The create service broker command works with `http`
Much appreciated!!

**Comment by chrislinan** [comment]
Hi, @dsabeti I met the same trouble, it's two years later, are there any fixes from the engineering team?

**Comment by dsabeti** [comment]
Hey @chrislinan. I'm no longer on the team responsible for cf-deployment. Let's rope in @vitreuz and @Syerram, who are currently on that team.
