### ISSUE TITLE
Ops File for compiled releases

### ISSUE THREAD

**Issue by tinygrasshopper** [cloudfoundry/cf-deployment#153]
Would it be possible to have opsFiles to replace [the releases section](https://github.com/cloudfoundry/cf-deployment/blob/171fede2351726a520286ab89986946da100be2a/cf-deployment.yml#L1481-L1569) with compiled releases per IaaS(or atleast for GCP). 

Currently multiple teams are waiting for the same releases to be compiled, is this project a good place for such a file to live?

**Comment by dsabeti** [comment]
@tinygrasshopper It's such a good place for this ops-file to live that [it already lives here!](https://github.com/cloudfoundry/cf-deployment/blob/master/operations/use-compiled-releases.yml) 

We're still working on getting all the releases compiled. You can follow that work [with this release marker](https://www.pivotaltracker.com/story/show/141059931).

As far as IaaS selection, it actually doesn't matter. Releases are compiled against stemcell operating systems (i.e. ubuntu-trusty) rather than IaaSes.

**Comment by dsabeti** [comment]
Hey @tinygrasshopper. Is that ops-file what you're looking for? If so, I'd like to close the github issue.

**Comment by tinygrasshopper** [comment]
Ok. Will follow that release marker
