### ISSUE TITLE
Add smoke-test errand to cf-deployment

### ISSUE THREAD

**Issue by bsnchan** [cloudfoundry/cf-deployment#17]
Once cf is deployed, we'd like to be confident that cf is running correctly. Can we add the smoke-test bosh errand into the cf-deployment manifest?

**Comment by dsabeti** [comment]
Hey @bsnchan seems reasonable that we should provide an easy way to smoke-test the deployment once you've bosh deployed. Does it need to be an errand? How would you and your team feel if we provided a concourse task instead?

**Comment by ryanmoran** [comment]
@dsabeti the smoke-tests are helpful to have as an errand so that they can be tested through BOSH, by folks who don't have a Concourse installation. Even though many teams within CF will probably benefit from a Concourse task, having an errand is still important because folks outside of CF want this without needing Concourse. Basically, as a minimum for what to expect from folks who run this, expect that they will have BOSH, but not Concourse.

**Comment by dsabeti** [comment]
@ryanmoran That makes sense. I'll prioritize the story.

**Comment by cppforlife** [comment]
@dsabeti @ryanmoran will be doing a round of polish on errands soon. planning to introduce a way to run errand off of existing service lifecycle machine.

**Comment by dsabeti** [comment]
This change is (finally) on master.
