### ISSUE TITLE
Duplicated variables for loggregator doppler cert?

### ISSUE THREAD

**Issue by rosenhouse** [cloudfoundry/cf-deployment#22]
[This commit](https://github.com/cloudfoundry/cf-deployment/commit/008939007842940a271badd966081812a19a513c) introduced new variables `loggregator_tls_doppler_cert` but the manifest already had a variable `doppler_tls_server_cert`.  

I think these ought to be the same thing.  

Loggregator's [own scripts](https://github.com/cloudfoundry/loggregator/blob/develop/scripts/generate-loggregator-certs) only generate 3 cert/key pairs, not 4.   And when we do a deployment and set `loggregator_tls_doppler_cert` to be different from `doppler_tls_server_cert` then metron fails to start.  But apparently when hermione is deployed using identical values for these two variables, then the deploy succeeds.

cc: @mcwumbly

**Comment by rosenhouse** [comment]
may be related to https://github.com/cloudfoundry/cf-deployment/pull/21

cc: @wfernandes @nelsam

**Comment by nelsam** [comment]
This is due to our old `metron->doppler` TLS code being really, really bad for large deployments (i.e. doppler's CPU usage skyrockets and it stops accepting data from metron).  We highly recommend changing metron's `protocols` property to just `udp` and scrapping metron's certs for the moment; once we update metron's TLS code, we'll make a new PR to add them back (and update our script to generate metron certs).

Technical details:
- Many goroutines writing to a single channel causes lots of lock contention.
- Metron opens one connection to every single doppler in a system.
- With UDP, you can have a single goroutine accept all packets coming in to a port.
- With TCP/TLS, there is one goroutine _per connection_.
- A sufficient number of metrons will _always_ cause massive lock contention, which causes doppler's CPU usage to spike until it's just churning on locks, barely ever actually reading data.  Because metron opens a connection to every doppler, this is not something that can be solved by scaling dopplers.

So we need to fix our pooling logic before metron can really communicate with dopplers over TLS.

**Comment by dsabeti** [comment]
Hey @nelsam. I'm confused, I think. Your comment seems to say that we should switch from TCP+TLS back to UDP. That seems reasonable. How exactly does this relate to Gabe's question? 

I see that there are two properties -- `doppler.tls.server_key` and `loggregator.tls.doppler.key` -- and they're both provided to the same job. To enable TCP+TLS, which of those properties do we need? To enable UDP only, which of these properties do we need?

/cc @wfernandes

**Comment by dsabeti** [comment]
@nelsam Never mind. I've looked through the spec files for metron, doppler, and traffic controller and see now that these certs have all been renamed. Is your recommendation still to use UDP instead? Will these properties be used by gRPC when it lands? If so, we'll likely keep the properties so we can use them again later.

**Comment by dsabeti** [comment]
Here's the story to remove the unused fields: https://www.pivotaltracker.com/story/show/134485055

**Comment by apoydence** [comment]
@dsabeti Yes, use UDP for a while.  Our new TLS properties are for `trafficcontroller<->doppler`; we haven't gotten TLS in metron finished yet.  The properties that *should* be used are `loggregator.tls.{trafficcontroller,doppler}.{cert,key}`.  When we get metron working, its properties will also be moved to a similar namespace (i.e. `loggregator.tls.metron.{cert,key}`).

**Comment by dsabeti** [comment]
@rosenhouse I'm going to close this issue since we have a story to remove the duplicate fields. Thanks for the feedback!
