### ISSUE TITLE
Updating instance consul_z1 fails while bosh deploy

### ISSUE THREAD

**Issue by fluppirt** [cloudfoundry/cf-deployment#260]
Hi,

i'm trying to install cloud foundry on openstack and ran into a problem.

![consul](https://user-images.githubusercontent.com/32242981/30877239-65ca7228-a2f9-11e7-97f2-b9973d55d526.png)

![unbenannt](https://user-images.githubusercontent.com/32242981/30877262-75a2be08-a2f9-11e7-9f6b-ab3ce4d8c6d5.PNG)

I've increased the timers in the Update Block of the deployment manifest and recreated the consul vm serveral times without success.

While checking the logs of the consul vm, i've noticed that the files
/var/vcap/jobs/consul_agent/config/certs/agent.crt
/var/vcap/jobs/consul_agent/config/certs/agent.key
are empty. Both key and certificate are included in the stub-file.

Also i've noticed that the other cert- and key-files in this directory are filled, but have a different line break compared to the stub-file and the deployment manifest.
It looks like one big string with a blank between each "line".

![format](https://user-images.githubusercontent.com/32242981/30877991-d0614362-a2fb-11e7-81b3-09f166f58fee.PNG)

If I replace the files in /var/vcap/jobs/consul_agent/config/certs/ by the original once created by cf-release/scripts, the consul_agent works fine.

Here are the logs:

[consul_agent.stderr.log](https://github.com/cloudfoundry/cf-deployment/files/1334568/consul_agent.stderr.log)
[consul_agent.stdout.log](https://github.com/cloudfoundry/cf-deployment/files/1334567/consul_agent.stdout.log)

I think something is going wrong when creating the deployment-manifest from the stub-file.

**Comment by dsabeti** [comment]
Hey @fluppirt. Happy to help with this issue, but I'd like to suggest an alternative first.

The output on your console suggests to me that you're using [cf-release](https://github.com/cloudfoundry/cf-release) instead of cf-deployment, this repo. (The `_z1` suffixes give it away.) Is this a new Cloud Foundry deployment, or is this an existing deployment that you're trying to upgrade. If it's new, I'd _highly_ suggest using cf-deployment instead. Our `develop` branch has instructions for deploying to Openstack:
https://github.com/cloudfoundry/cf-deployment/tree/develop/iaas-support/openstack

If this is an existing environment that you need to upgrade in-place, let me know and I can try to help with your stub file.

**Comment by fluppirt** [comment]
Hey @dsabeti,

thanks for the quick response. It's a completely new deployment. What's the difference between cf-release and cf-deployment?

For the installation i'm following the steps from cloudfoundry.org
https://docs.cloudfoundry.org/deploying/openstack/

Thanks for your help!

**Comment by dsabeti** [comment]
cf-release is going to be deprecated very soon, and cf-deployment is the new recommended way to generate deployment manifests.

There are lots of differences between the two, but maybe the most pertinent one is that is uses a handful of newer BOSH features the cf-release manifest generation can't. The result is a manifest that is considerably simpler to work with. Importantly, cf-deployment uses the bosh CLI for generating credentials -- including mutual TLS certificates, which are the cause of current issues -- so that operators don't have to.

The docs on docs.cloudfoundry.org will be replaced _very_ soon with a link to the same page that I link you to. You happened to catch us in the transition window.

**Comment by dsabeti** [comment]
Hey @fluppirt, any luck using cf-deployment?

**Comment by fluppirt** [comment]
Hi, 

sorry for my late reply. I've found my mistake.
I had forgotten to put a pipe-symbol ( | ) in front of every key end cert. 
After solving that all instances were updated successfully and i've got cf-release running.

@dsabeti thanks for your help!

(Sorry for my bad english)
