### ISSUE TITLE
Duplicate logs when using syslog-release addon

### ISSUE THREAD

**Issue by achawki** [cloudfoundry/cf-deployment#292]
Hi,

we were not sure where to open this issue. It is more an overall cf and logging issue.

With `cf-deployment` v0.33.0 (cf-release `v277`) (i.e. Loggregator v99) log forwarding by `metron agents` has been removed. Thus we integrated the `syslog-release` addon via `runtime-config` ([enable-component-syslog.yml](https://github.com/cloudfoundry/cf-deployment/blob/master/runtime-configs/enable-component-syslog.yml)). As a result we saw that many logs (e.g. from `cloud_controller`) are now duplicated in our logging infrastructure.

The reason for this is that the syslog-release enables `blackbox` [by default](https://github.com/cloudfoundry/syslog-release/blob/72f4f8cd2ce2f5a6455e21a90923a51a976f0852/jobs/syslog_forwarder/spec#L26) which is forwarding all log files from `/var/vcap/sys/log` to `syslog`. At the same time components write to syslog directly (e.g. cloud controller uses steno and [configures writing to syslog](https://github.com/cloudfoundry/cloud_controller_ng/blob/77fca99c03191de41a069db76a0d6222deb6596d/bosh/jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb#L108)). The same applies to other jobs.

We decided to disable `blackbox` for now (i.e. changed the `runtime-config`), but are unsure about the future plans. Will components stop writing to syslog directly and rely on `blackbox`?

**Comment by dsabeti** [comment]
Hi @achawki. Thanks for bringing this to our attention. 

We actually did an investigation early on to see if there would be duplicate logs sent to syslog drains, and (at the time) we found that we weren't getting duplicates. It sounds like we should retry the experiment.

Before that, can we get a rundown of your environment, so we can try to reproduce? For example, which IaaS and stemcell are you using? What service are you using for your syslog drain (papertrail, ELK, etc.)?

One quick fix we may do in the meantime is disable the `blackbox` config until components stop writing to syslog directly.

**Comment by achawki** [comment]
The default of whether `blackbox` is enabled has changed to `true` with https://github.com/cloudfoundry/syslog-release/commit/0e06601e6df5070ef3ddf52c1235eadde651425a about half a year ago, maybe after you did your tests?

We are using ELK, AWS (among other infrastructures) and Stemcell `bosh-aws-xen-hvm-ubuntu-trusty-go_agent/3445.11`, but it seems unrelated to our setup.

**Comment by dsabeti** [comment]
Ok, thanks @achawki, we'll have someone dig into this soon.

**Comment by anEXPer** [comment]
@achawki, I'm investigating this issue with one of our environments. I'm not seeing duplicate logs, but it's a difficult thing to spot-check for, especially if not all logs are duplicated. Was there a particular type of log that you were seeing always-duplicated? If you could give me a few examples of specific log lines that were duplicated, that would be very helpful.

Thanks!

**Comment by jmprice** [comment]
We have been experiencing this issue as well and I think I understand what is happening and how to fix it.

Most components, either in their start control scripts or via some other method, send their logs to the /var/vcap/logs/*/ dir and to rsyslog after pre-pending "vcap." to the component name.

`    exec 1> >( tee -a $LOG_DIR/garden.stdout.log | logger -p user.info -t vcap.garden ) \`
`            2> >( tee -a $LOG_DIR/garden.stderr.log | logger -p user.error -t vcap.garden )`

For these logs sent to rsyslog:
Because the file /etc/rsyslog.d/rsyslog.conf is processed after the default rules found in 50-default.conf, this rule: `:programname, startswith, "vcap." ~`, which prevents them from being sent anywhere else isn't applied until after the logs have already been forwarded by the default rules to /var/log/syslog, messages, user, etc.  So we have CF logs going into multiple local logs and being sent to a remote system.

Blackbox forwards all logs in /var/vcap/sys/log/\*/\* to rsyslog and sets the hostname field to "-" but does not insert "vcap." into the message.  There is no rule to identify these logs and drop them before being sent to the local /var/log/* files, so now we have 2 sources putting the same logs in the local files and forwarding them but with slightly different formatting:
`2017-10-26T20:45:02.829986+00:00 localhost vcap.route-emitter: 
 "timestamp":"1509050702.829935074",...`
`2017-10-26T20:45:02.834259Z - route_emitter {"timestamp":"1509050702.829935074",...`

So it seems like a few things need to happen.
1)  Rename the rsyslog.conf file that is put in /etc/rsyslog.d/ so that it is processed before the 50-default.conf file.  00-rsyslog.conf seems like a good name.
2)  If Blackbox is enabled, change the 00-rsyslog.conf (formerly rsyslog.conf) so we drop all the "vcap." logs before they are sent anywhere by moving the vcap rule above anything that sends logs to a remote server.
`# Prevent vcap.* messsages from reaching anywhere else`
`:programname, startswith, "vcap." ~`

3)  Blackbox doesn't seem to allow you to add any unique identifier like "vcap." but does set the the hostname to "-" so that is all we have to use as a filter.
Add a rule at the end of the file to drop anything from blackbox so they don't go to the local /var/log/* files
`# Prevent messsages sent via blackbox from reaching anywhere else`
`:hostname, isequal, "-" ~`

4)  In the long term, if the plan is to only have blackbox sending logs, the CF components themselves should be changed to only log to a local file.

**Comment by selzoc** [comment]
Hi @achawki @jmprice we've opened [an issue on syslog-release](https://github.com/cloudfoundry/syslog-release/issues/31).

As mentioned in that issue, we are also going to disable blackbox in the `cf-deployment` opsfile as a short-term mitigation.  This shouldn't result in the loss of any log messages since no `cf` components are using blackbox yet.

Once the issue with syslog-release is resolved, we'll re-enable blackbox.
