### ISSUE TITLE
Default max_in_flight: 5 seems too high when most instance groups default to 2 instances

### ISSUE THREAD

**Issue by SocalNick** [cloudfoundry/cf-deployment#326]
https://github.com/cloudfoundry/cf-deployment/blob/master/cf-deployment.yml#L6

In our limited experience with cf-deployment, we have to override this default to 1 and only increase `max_in_flight` for api, doppler, and diego-cell instance groups. Even with a rather large number of apis and dopplers, we don't feel it's appropriate to have `max_in_flight: 5`. Our `max_in_flight` for diego-cells is not yet determined.

**Comment by dsabeti** [comment]
Hey @SocalNick. Thanks for this feedback. I've got a few questions:
1. What's the impact of using a higher `max_in_flight` than 1 for most jobs? I'm asking because we actually specifically set `max_in_flight: 1` for some jobs that we knew would be negatively impacted by a quick rollout -- [consul, for example](https://github.com/cloudfoundry/cf-deployment/blob/162a8f1b065d90bf4fbbbb401a306f0ed35a4e1b/cf-deployment.yml#L64-L65).
2. For things like `doppler` and `api`, what value do you use for `max_in_flight`? How did you arrive at that number?
3. In general, how do you determine preferred values for `max_in_flight`?

Luckily, these are not values that move locations in the manifest, so this is something we can iterate on without breaking anybody's tooling or ops-files.

**Comment by dsabeti** [comment]
Hey @SocalNick. After discussion before the holiday, we decided that it made sense to default to 1 in cf-deployment because there is no other max_in_flight value that makes sense generically.

For example, Diego Cells can certainly be deployed more than one at a time. However, the correct value for max_in_flight on the Diego cells depends on how many cells an operator has deployed, the app load on each cell, and the SLA the operator wants to provide to the users. If we stuck with `max_in_flight: 5`, and an operator had 5 cells deployed, then the deploy would have the following timeline:
1. Cell canary (instance 1) starts draining.
2. App instances are started up on cell instances 2-5.
3. Cell canary restarts.
4. Because we set `max_in_flight: 5`, cell instances 2-5 all begin draining.
5. All app instances start up on cell instance 1. If the cell is big enough, this could be fine; however, the most likely outcome is that cell instance 1 cannot start all the app instances.

So, we've set the value to 1 for everything in this commit: https://github.com/cloudfoundry/cf-deployment/commit/85912cddf56c7028b90b8ac11592429edf5b941b
