### ISSUE TITLE
Unexpected downtime for user provided syslog drains when upgrading to cf-deployment 1.0

### ISSUE THREAD

**Issue by ahevenor** [cloudfoundry/cf-deployment#336]
Working through the migration the changes in cf-deployment 1.0 which moved syslog-adapters to a separate instance group meant the adapters did not receive drain details until a new syslog-scheduler was deployed resulting in disruption of user-provided syslog drains. 

cc @JohannaSmith @bradylove @coreyti

**Comment by dsabeti** [comment]
@ahevenor @JohannaSmith @bradylove. Let me make sure I understand the problem:
1. The adapters are told about syslog drains by the scheduler.
2. The scheduler discovers the adapters via BOSH links.
3. Because the adapters are updated before the schedulers, they don't get any information about syslog drains until the schedulers have been updated.

Given that, what's the mitigation? Should the adapters be updated at the end of the deployment? We moved them up in the deployment also to avoid syslog drain downtime when migrating to cf-deployment 1.0. When the adapters were getting deployed at the end, we had the following:
1. `doppler` instance group gets updated not to have adapters
2. Most of the CF gets deployed
3. `adapter` instance group gets its code update

Between (1) and (3), there were no adapters anywhere in the platform.

cc @staylor14 @selzoc

**Comment by dsabeti** [comment]
I think this issue has been resolved since cf-deployment 1.0. The adapters are deployed before the dopplers or the scheduler, so those jobs should be able to successfully use the link. I'm going to close the issue out, but feel free to re-open.
