### ISSUE TITLE
App  container network problem.

### ISSUE THREAD

**Issue by geekyzk** [cloudfoundry/cf-deployment#435]
Hi team:
    When i push a demo app,  it configration connect to ccdb database,but it not connect to db.In my pc , use mysql cli or use ide run app are  connect successful . Is this because of the problem of the container's network configuration?How should I configure?
    I configuration ccdb is `root@%` or connect other db is fail too.

**Comment by dsabeti** [comment]
Hi @geekyzk. By default, application security groups do not allow network connections between containers and private IP addresses -- including the internal CCDB. In general, I'd highly recommend using the CC API instead of attempting to access the CCDB directly as it poses both security and data synchronization risks, but if this is merely a demo, you can look at the Application Security Group docs for how to update them in order to allow traffic to private IPs.

**Comment by geekyzk** [comment]
Hi @dsabeti , I update[ cf-deployment](https://github.com/cloudfoundry/cf-deployment/blob/master/cf-deployment.yml#L607-L619) , but in cf system 
```
Name    public_networks
Rules
	[
		{
			"destination": "0.0.0.0-9.255.255.255",
			"protocol": "all"
		},
		{
			"destination": "11.0.0.0-169.253.255.255",
			"protocol": "all"
		},
		{
			"destination": "169.255.0.0-172.15.255.255",
			"protocol": "all"
		},
		{
			"destination": "172.32.0.0-192.167.255.255",
			"protocol": "all"
		},
		{
			"destination": "192.169.0.0-255.255.255.255",
			"protocol": "all"
		}
	]
```
it not update config. In existing systems, can only be configured through the command line?

**Comment by dsabeti** [comment]
Yeah, you've stumbled onto a very common mistake. The values in the manifest only work _on the first_ deploy of the Cloud Controller. (cc @zrob)

If you want to change or create new security groups after that, you have to use the CF CLI and run `cf create-security-group` or `cf update-security group`. Don't forget to bind your security groups as well. You can find more information about security groups [here](http://docs.cloudfoundry.org/concepts/asg.html).

**Comment by geekyzk** [comment]
Thanks.
