### ISSUE TITLE
Expiration time of CAs

### ISSUE THREAD

**Issue by achawki** [cloudfoundry/cf-deployment#448]
Hi,

according to https://docs.google.com/document/d/1vKxziTEvIgKHubukoyAGaJzGqrMBjun7JffbunlLBPg/edit#heading=h.wftyivqbaag4 it is not possible to rotate the CAs without a downtime of the CC API.

One mentioned possible solution is `Possibility #3: Don’t solve this problem, but increase CA validity period`
> If CAs are generated with a 5 year validity period...

CAs are currently specified as `variables` and `bosh` `interpolate` is used to generate them. 
The expiration is currently hardcoded to 1 year https://github.com/cloudfoundry/config-server/blob/74c334a625d0491bf3462f57719cef3c0d2828af/types/certificate_generator.go#L157
It is currently not possible to change that: https://github.com/cloudfoundry/bosh-cli/issues/273

A hardcoded CA expiry duration of 1 year combined with the fact that CA rotation is not possible without a downtime is a problem.

**Comment by dsabeti** [comment]
Hi @achawki. Yep, it's definitely a problem. That's why we wrote up the doc and started proposing ways to fix it.

Honestly, I don't think changing the CA expiration time is a solution to the problem -- it just delays a solution, and it delays it until a time when everyone will have forgotten about this issue and lost context. I think a better solution is to address the problem in CAPI.

Also, it would probably be better to discuss this topic further in that doc, since it gives context on the problem and outlines a few potential solutions. Anyone should have access to comment and make suggestions on the doc, so any input or ideas you have would be more valuable there.

**Comment by achawki** [comment]
Hi @dsabeti,

ok thanks. We will move the discussion to the CAPI document and the bosh-cli issue.
