### ISSUE TITLE
AWS loggregator port override

### ISSUE THREAD

**Issue by jmcarp** [cloudfoundry/cf-deployment#468]
According to the [operations docs](https://github.com/cloudfoundry/cf-deployment/blob/master/operations/README.md), the loggregator has to listen on a separate port (4443) from the main http listener. That might be the case for classic aws load balancers, but aws application load balancers support websockets and don't require a separate port/listener. It would be helpful to clarify that the limitation references in the docs only applies to legacy elbs, and ideally to recommend albs in bbl and elsewhere in docs.

**Comment by dsabeti** [comment]
Yeah, a lot of these ops-file were written either before application LB's were released (or before anyone had tried them with CF, not sure which), and so we didn't consider them when writing those docs. We should definitely update them to clarify that these only hold for "classic" ELBs. I'm happy to prioritize this as a story. We'd also gladly merge a PR.

Just to have a visible place to discuss this, I think @evanfarrar (cc @genevieve) wanted [bb](https://github.com/cloudfoundry/bosh-bootloader) to support application load balancers in addition to (or instead of?) classic ELBs.

**Comment by dsabeti** [comment]
Hi @jmcarp. I've been digging through dormant github issues and found this again. Here's a commit to update the documentation about `aws.yml`: https://github.com/cloudfoundry/cf-deployment/commit/5eb1ae36ba28f3f66037a63e2d297e8af3de3c62

**Comment by heyjcollins** [comment]
Since there's been no response on this issue since May, I'm going to close it. If you'd like to see it re-opened, please comment on the issue and reopen.
