### ISSUE TITLE
Why skip ssl validation by default?

### ISSUE THREAD

**Issue by jmcarp** [cloudfoundry/cf-deployment#542]
It looks like ssl validation is generally turned off by default, and then optionally turned back on with ops files like https://github.com/cloudfoundry/cf-deployment/blob/master/operations/stop-skipping-tls-validation.yml. But if I add another ops file, like https://github.com/cloudfoundry/cf-deployment/blob/master/operations/enable-nfs-volume-service.yml, I have to notice that ssl validation is turned off and add a custom ops file to turn it back on.

Why not validate ssl by default? IMO that's the more typical / more secure default.

**Comment by heyjcollins** [comment]
Hey @jmcarp - thanks for submitting this issue. IMHO - we should be secure by default and I don't know why we aren't.

I've transformed the tracker story into a charter to look into what it would take to make SSL validation default and bumped it up in priority.

https://www.pivotaltracker.com/story/show/158560549

**Comment by dsabeti** [comment]
Hey, I can actually speak to this a bit. The short answer is to enable CI / development environments. There are a few tests in CATs that push apps, and some internal components like the Cloud Controller interact with those apps. If we don't skip validation, then all dev and CI environments would have to procure trusted certificates in order for tests to pass. Instead of adding that complication, we decided to skip TLS validation on those components, and provide an ops-file to "productionize" the deployment for those operators who have trusted certificates.

**Comment by heyjcollins** [comment]
This comes down to making call between the, sometimes competing, needs of production operators and the CF component developers. Our current position is to favor the component developer when faced with decisions like these because our goal is to optimize for the continued rapid development of the platform as a whole. As such, I'm going to close this issue.
