### ISSUE TITLE
 No qualifying bean of type [org.springframework.mail.javamail.JavaMailSender] while deploying service into PCF

### ISSUE THREAD

**Issue by Arjun09** [cloudfoundry/cf-deployment#56]
Hi I am trying to deploy a service which uses Spring Mail to send email. The service is working in my local IDE and I am trying deploy it in PCF cloud. I did a gradle build and have manifest.yml file on the class path. When I push it the app failed start with following exception. Is that something I am missing or PCF behaviour or email service will not in cloud?

I am using spring boot and I have all the required properties which helps to create a bean for mail in my application.properties file.

`Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.springframework.mail.javamail.JavaMailSender com.send.SendController.mailSender; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [org.springframework.mail.javamail.JavaMailSender] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}`

**Comment by dsabeti** [comment]
Hey @Arjun09, thanks for opening this issue. Unfortunately, this isn't really the correct place to open this discussion. `cf-deployment` is an OSS deployment manifest for deploying CF; it doesn't actually have any of the code related to pushing apps or binding services.

No matter -- I'll help you find the right place to ask about this. I'd say you have a few better places to ask about this:
1. The [java buildpack](https://github.com/cloudfoundry/java-buildpack) repository. The buildpack is the component that gets your app ready to be run by the CF platform. The team that manages that repository has the knowledge for running Java apps on CF.
2. [Pivotal CF support](https://support.pivotal.io/). Since you're using a vendor, you can reach out to them for help as well, and they typically have infrastructure for delegating your question to the people who can best help.

I hope that helps. Feel free to come back to this issue with updates -- sometimes it's helpful to leave the resolution in the public github issue, so that others can see this in google search results if they see the same problem.

**Comment by dsabeti** [comment]
Hey @Arjun09. I'm going to close this issue due to inactivity. Feel free to re-open it if you think that there's additional discussion worth including in this public forum.
