### ISSUE TITLE
The version of cf-networking-release in use-compiled-releases-xenial-stemcell.yml is inconsistent with cf-deployment.yml

### ISSUE THREAD

**Issue by bingosummer** [cloudfoundry/cf-deployment#569]
### What is this issue about?

In https://github.com/cloudfoundry/cf-deployment/blob/v2.9.0/cf-deployment.yml#L1643-L1646, the version of cf-networking is v2.8.0.
In https://github.com/cloudfoundry/cf-deployment/blob/v2.9.0/operations/experimental/use-compiled-releases-xenial-stemcell.yml#L28-L36, the version of cf-networking is v2.9.0.

### What version of [cf-deployment](https://github.com/cloudfoundry/cf-deployment/releases) are you using?

v2.9.0

**Comment by heyjcollins** [comment]
Hi @bingosummer - cf-networking 2.9.x is not compatible with cf-deployment unless bosh-dns is enabled. We're in the process of getting BOSH dns enabled by default in cf-deployment v3.0 due to release this week. Once that work is completed (or once cf-networking release is updated to be compatible with cf-deployment without bosh-dns enabled) we'll unpin the cf-networking release and you should be good to go. 

Thanks for bringing this issue to our attention!

Josh
