### ISSUE TITLE
log-cache component

### ISSUE THREAD

**Issue by michaelgrifalconi** [cloudfoundry/cf-deployment#586]
### What is this issue about?

Since cf-deployment v3.0.0, log-cache-release is **enabled by default**. This led us to a few questions.

#### Experimental component?

[On the component's README](https://github.com/cloudfoundry/log-cache-release#log-cache-release) you find the following text.

> Log Cache Release is a bosh release for Log Cache. It provides an **experimental** in memory caching layer as a **potential future alternative** for cf logs --recent and container metrics retrieval.

_Is the component still in an experimental stage of development or is the README out of date?_

#### Designed for large-scale deployment?

In the same README, same sentence there is a link to[ this document that explains the architecture of log-cache](https://docs.google.com/document/d/1yhfl0EB_MkHkh4JdRZXGeQMx_BDMCuB-SpPuSrD3VOU/edit#).

> For operators of large platforms this improved performance would be worth the additional required components, but for smaller deployments this would add additional footprint to loggregator. That said this component could likely be collocated with Traffic Controller and Reverse Log Proxies for most deployments. 

This is described as a component made to improve performance on large platforms, but on cf-deployment it is by default colocated with dopplers and **there is no ops-file to move it out as a separate VM**, only one to disable it.

Digging into the log-cache-release, we found an ops file to use it as standalone job, but it was removed with [this commit ](https://github.com/cloudfoundry/log-cache-release/commit/5f9964f05e915e3ad6120244e51eedaa74b9f003#diff-a61d1992b3330113e5ad47498878369a)

In the same [README](https://github.com/cloudfoundry/log-cache-release#cache-duration--scaling)
> ... more recent testing with this colocation strategy has not met these SLO's. If targeting these SLO's is critical to your foundation we recommend using a log-cache instance group.

_Is this information still current? 
Will we get an ops file to cf-deployment/operations in future?
Is it advisable to keep it colocated on a system with >30 doppler VMs?_

Thanks and regards,
Michael

**Comment by tyyko** [comment]
Hello @heyjcollins, 

as you mentioned on #622 that log-cache won't be optional for long, could you please have a look at the questions on this issue?

Thanks!

**Comment by hdub2** [comment]
Hey @tykko - the text of the README is under review. As of today, log-cache has been deployed using the doppler colocation strategy on Pivotal's hosted, cf-deployment-based environment since July, servicing a very high volume of traffic. The README's intent was to express that, as a FIFO in-memory cache, log-cache will provide retention of traffic over longer periods when provided with additional resources. Other component teams are beginning to rely on log-cache, so I think that the answer is indeed that it won't be optional for long.

**Comment by heyjcollins** [comment]
@michaelgrifalconi - I'd encourage you to reach out to the [log-cache team via slack](https://cloudfoundry.slack.com/messages/CBFB7NP9B) about a dedicated instance group but we've been successfully running a colocated configuration of log-cache in our large Pivotal hosted foundation for about 4 months. and all is well. As such, we're going to remove the ops file to disable log-cache in the next major release.

I'm going to close this issue and if you'd like to continue the dialogue here rather than directly with the log-cache team please feel free to reopen.
