### ISSUE TITLE
Wrong version of xenial stemcell in v3.2.0 release notes

### ISSUE THREAD

**Issue by bingosummer** [cloudfoundry/cf-deployment#590]
`97.5` is used in https://github.com/cloudfoundry/cf-deployment/blob/v3.2.0/operations/experimental/use-xenial-stemcell.yml
But in v3.2.0 release notes, it's `97.3`.

**Comment by bingosummer** [comment]
CC: @ishustava

**Comment by ishustava** [comment]
Thanks @bingosummer! I've updated release notes.

**Comment by gerhard** [comment]
In commit https://github.com/cloudfoundry/cf-deployment/commit/f89321146ebd6bf0f1e03a6894272e67986c0943 the bot missed to update all instances of ubuntu-xenial: https://github.com/cloudfoundry/cf-deployment/blob/f89321146ebd6bf0f1e03a6894272e67986c0943/operations/experimental/use-compiled-releases-xenial-stemcell.yml#L235-L369

It doesn't make sense to submit a PR against this repo since the change needs to be made in the tooling that manages the xenial stemcell version. Hope this helps.
