### ISSUE TITLE
UAA Integration in CF Deployment for Multi IaaS

### ISSUE THREAD

**Issue by JY-Lee** [cloudfoundry/cf-deployment#613]
While deploying CF Deployment in multi IaaS environment (for example: AWS and Openstack ), is it possible to use only one UAA server component of one side ( either AWS or Openstack) and have it integrated for both (enable UAA login for both IaaS by one UAA server component ) ?
The ideal scenario is to have AWS CF Deployment allocate public IP for UAA VM in AWS environment and have Openstack CF Deployment use AWS UAA as its UAA component. 

Any advice or reference would be appreciated. Thank you in advance.  

Best,
JY

**Comment by ishustava** [comment]
Hey @JY-Lee,

This is a pretty broad question, and I'm not entirely sure if it's possible.

Assuming you have infrastructure set up for this (i.e. security group rules etc.), I can think of the following you can look into to get started:
1. For components that use external UAA URL `uaa.((system_domain))`, you need to make sure that domain name points at the IP of the UAA VM on AWS.
1. For components that use internal UAA URL `uaa.service.cf.internal` via consul or BOSH DNS, you need to make sure to overwrite them with an external URL (e.g. [routing-api job in the routing release defaults to the internal URL](https://github.com/cloudfoundry/routing-release/blob/50862b402322cf902d4784d675f8ea4fe2ca2fee/jobs/routing-api/spec#L100))
1. UAA certificate should have correct Subject Alternative Names (SANs) so that TLS verification will work: https://github.com/cloudfoundry/cf-deployment/blob/33abec0e839f8beb572c922fd2e8c870c3617bda/cf-deployment.yml#L2080-L2086

Hope this helps!

**Comment by JY-Lee** [comment]
@ishustava It was helpful. Thank you very much! :)

**Comment by heyjcollins** [comment]
@JY-Lee,

Looks like you got the assistance you needed.
I'm going to go ahead and close this out.

Please feel free to reopen it if you need to discuss further.

Cheers,

Josh
