### ISSUE TITLE
Feature Request: Is there any alternatives to configure UDP_Router for CF Components

### ISSUE THREAD

**Issue by abhilash07** [cloudfoundry/cf-deployment#647]
Hi everyone we all know that we have go_router & tcp_router's to receive data on http and tcp protocols respectively.We are planning Smartcity platform over CF PaaS, all the data should be transmitted on UDP protocols only. 

In that case we should have udp_router similar to go_router & tcp_router's. I have looked into below link regarding this issue (https://www.youtube.com/watch?v=FSZKhtxnRXk). But unfortunately this OpenSource (https://bitbucket.org/grapeup/profile/repositories) is not supported anymore.

Is CF community have any Roadmap on udp_router (or) is there any alternative OpenSource solutions for this issue.

Thanks in advance.

**Comment by Changdrew** [comment]
Hello @abhilash07, there currently is no option/feature to enable something like udp_router in a similar manner to go_router/tcp_router. However, we are looking into whether or not there is a roadmap in order to implement udp inside the either the OSS/commercial version of CF. It seems that there are some ways to configure certain components, as seen [here](https://docs.cloudfoundry.org/concepts/understand-cf-networking.html), but not all components support udp. We hope to get back to you soon once we formulate a more definitive answer.

**Comment by shubhaat** [comment]
Hi @abhilash07 , 

Currently the CF Routing team is focussing on implementing a Istio and Envoy based routing plane, you can read more about it [here](https://docs.google.com/document/d/1LgLY0g39fzpg1_4zTckbH1mOuuSKGvYwp2tkakoe9ys/edit). We are tracking the Envoy communities efforts to [support UDP](https://github.com/envoyproxy/envoy/issues/492). Currently we do not have a plan to support UDP, but we would love to hear your usecase and talk to you about the criticality of this for you.

**Comment by wrowe** [comment]
@abhilash07 do you have a summary of the specific UDP protocols which their Smartcity app is designed around?

We ask because UDP can be implemented with less state information for higher layer protocols which contain additional routing information.

**Comment by heyjcollins** [comment]
Since there's been no response to this issue for a few weeks I'm going to go ahead and close it out.
Please comment and reopen if you'd like to continue the dialogue.

**Comment by gm2552** [comment]
Been wanting to implement this use case (simple SpringBoot service) for quite some time and requires a UDP router.

https://directprojectjavari.github.io/dns/
