### ISSUE TITLE
Colocate Smoke tests on an existing VM?

### ISSUE THREAD

**Issue by geofffranks** [cloudfoundry/cf-deployment#650]
Any thoughts on updating cf-deployment to put the smoke_tests errand on an existing VM/instance-group, like clock_global, to speed up test running?

**Comment by heyjcollins** [comment]
Hey @geofffranks,

Thanks for suggesting this.

We looked at our pipelines which run the errand and found (on GCP) that running the errand takes about 5 minutes with about 1/2 that time taken spinning up the VM. So colocating could save approximately 2-3 minutes.

The primary reason making this change gives me pause is if the VM where smoke-tests is colocated is scaled, BOSH will execute smokes on every VM in parallel unless the `--instance` variable/flag is included in the `bosh run errand` command.

While this is an interesting idea with some time savings, I'm not sure the time saved is worth the increased complexity of adding an additional ops file to cf-d and also of the user experience actually running the command and lastly the potential risk that running smokes colocated with other jobs may introduce.

Colocating smokes with other jobs is certainly doable and if operators wish to deploy with such a configuration, it would be easy to write a custom ops file for it and rather than supporting this via supported/tested ops file, it makes more sense for operators to manage this on their own.
