### ISSUE TITLE
CF java applictions restarting with exist status 148

### ISSUE THREAD

**Issue by ramarao2010** [cloudfoundry/cf-deployment#673]
### What is this issue about?

Hi,
We have observed in production that several cf app instances has been restarted automatically with exit status 148. Around 22 instances has been restarted due to this and it was an abnormal behavior as per our experience with cloudfoundry. Below is the log that we can see in events, but we couldn't identify any details related to the exit status. Something might have triggered these crashes and we need to identify the cause. Can someone suggest anything on this please ?

2018-12-01T01:54:31.00+0000   app.crash                  myaccount             index: 1, reason: CRASHED, exit_description: APP/PROC/WEB: Exited with status 148

### What version of [cf-deployment](https://github.com/cloudfoundry/cf-deployment/releases) are you using?

v2.3.0

### Please include the `bosh deploy...` command, including all the operations files:

[bosh deploy command here]

### Please provide output that helps describe the issue:

2018-12-01T01:54:31.00+0000   app.crash                  myaccount             index: 1, reason: CRASHED, exit_description: APP/PROC/WEB: Exited with status 148

### What IaaS is this issue occurring on?

AWS

### Is there anything else unique or special about your setup?

[Description here]

### Tag your pair, your PM, and/or team!
_It's helpful to tag a few other folks on your team or your team alias in case we need to follow up later._

**Comment by Changdrew** [comment]
Hi @ramarao2010, are you using version 2.3.0 of cf-deployment, or v2.3.0 of pcf-deployment?

**Comment by heyjcollins** [comment]
Hi @ramarao2010 - @Changdrew was asking actually whether you're using the open source CF (cf-deployment) or the commercial distribution of CF from Pivotal (pcf-deployment)

**Comment by ishustava** [comment]
Hey @ramarao2010,

Assuming you are using cf-deployment `v2.3.0`, could you also provide us with the following information:
1. Your full app log (with any credentials redacted) so that we can better tell what was happening to the app.
1. Your bosh deploy command. It's important for us to know the bosh command to determine which features you are enabling in your deployment.

It might be good to know what was common about the crashed apps other than being Java applications. For instance, did all the crashed apps run on the same `diego-cell` VM?

**Comment by ario2025** [comment]
I have the same problem here, but in Bluemix, and gosh, only 11 days to close a thread?

**Comment by heyjcollins** [comment]
Hey @ario2025,

Thanks for reaching out. I’ll reopen this issue so we can continue the dialogue with you.

A few questions/requests:

1. Areyou are using cf-deployment v2.3.0 (as referenced in the original issue submission)?
2. Could you provide us with the following information:
- Your full app log (with any credentials redacted) so that we can better tell what was happening to the app.
- Your bosh deploy command. It's important for us to know the bosh command to determine which features you are enabling in your deployment.
- It might be good to know what was common about the crashed apps other than being Java applications. 
  - For instance, did all the crashed apps run on the same diego-cell VM?

**Comment by cdutra** [comment]
@ramarao2010 @ario2025 Are you still having this issue?
Since this is an java application it should be using the java_buildpack to stage your help. The buildpacks team might be able to help you in debugging this issue, you can contact them https://github.com/cloudfoundry/java-buildpack or [on their slack channel](https://cloudfoundry.slack.com/messages/C02HWMDUQ/convo/C0FAEKGUQ-1556127944.096300/).

Thanks!

**Comment by Syerram** [comment]
Closing due to no response to this thread. If this is still an issue, please reopen the issue.
