### ISSUE TITLE
Doesn't use default cloud config

### ISSUE THREAD

**Issue by wfernandes** [cloudfoundry/cf-deployment#68]
Should cf-deployment use the default cloud-config from cloudfoundry/bosh-deployment and then use ops files to switch what type of VM/Disk to use?

/cc @apoydence

**Comment by dsabeti** [comment]
@wfernandes I think it's an interesting idea, but I think the those cloud configs are more for serving as an example than for actual use with Cloud Foundry (@cppforlife can correct me if I'm wrong).

For example, if you look at the [GCP cloud config](https://github.com/cloudfoundry/bosh-deployment/blob/master/gcp/cloud-config.yml), it adds a bunch of parameterized variables, some of which we'd want cf-deployment/bbl to control. It also adds a VIP network that we don't need. There are only two VM types even though cf-deployment wants more.

Anyway, I'd love for there to be standard cloud config for each IaaS that everyone case use. @evanfarrar, is there a plan to start using bosh-deployment instead of `bosh-init`? Would it make sense to make PR changes to the cloud configs in bosh-deployment so that they match CF's requirements. (FWIW, we could also change cf-deployment to match these, but I think the current cloud configs wouldn't work.)

**Comment by dsabeti** [comment]
I'm going to close this issue, but feel free to re-open if you thing there's more to discuss. Like I said, I'm pretty sure the cloud configs in bosh-deployment are examples and not tailored to CF.

**Comment by enocom** [comment]
@dsabeti I agree that specifying a default would be better. Often, users don't care about a particular VM type or disk type. If they do, it's easy enough to write ops files to change those settings.
