### ISSUE TITLE
Support release and stemcell caching by intermediate proxies

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry/cf-deployment#697]
### What is this issue about?

As a cf operator, in order to speed up deployments of cf that requires fetching remote internet stemcells/releases, I would like that releases and stemcells URLs included in the cf-deployment.yml manifest to be cacheable by intermediate caches (such as a corporate http proxy). 

Bosh director does support explicit [http proxy](https://bosh.io/jobs/director?source=github.com/cloudfoundry/bosh&version=268.4.0#p%3denv) (or could use transparent caching proxies) for downloading releases and stemcells.

In order for an intermediate proxy server to cache release and stemcells, the URLs can't use the HTTPS scheme and instead use plain http scheme. Integrity of the downloaded file over plain http will then be verified by bosh director by checking the sha1 present in the manifest. 

Many distribution systems such as debian/ubuntu or [TUF](https://github.com/theupdateframework/specification/blob/master/tuf-spec.md) don't mandate use of TLS and leave the option of using plain http + integrity checks (although TUF also includes expected file length in addition to hashes, likely to avoid DOS attacks by MITM that would return too large content and could fill up the bosh director disk).

See request for related support in bosh.io at https://github.com/bosh-io/web/issues/41

### What version of [cf-deployment](https://github.com/cloudfoundry/cf-deployment/releases) are you using?

v7.0.0

**Comment by heyjcollins** [comment]
Hey @gberche-orange,
This is an interesting use case which could be valuable to solve. I see you've logged an issue against bosh.io as well. I'm in touch with folks on the bosh team about this and I'd like to focus further dialogue on a single issue rather than across cf-deployment and bosh.io. 

Once the discussion within the bosh.io issue takes it's course, I should have more clarity on providing a solution within cf-deployment that could be generally applicable for operators.

As such, I'm going to close this issue out and track the bosh.io issue discussion.

**Comment by gberche-orange** [comment]
ok thanks @heyjcollins
