### ISSUE TITLE
`name:` missing after generating manifest

### ISSUE THREAD

**Issue by voelzmo** [cloudfoundry/cf-deployment#7]
The aws stub as described in [the documentation](http://docs.cloudfoundry.org/deploying/ec2/cf-stub-aws.html) is missing `meta.environment` which leads to `Deployment name not found in the deployment manifest` when actually deploying the result. I don't know why this would work for people not using the cf-deployment toolchain, but probably this should be fixed in the documentation then?

**Comment by voelzmo** [comment]
This is probably because the documentation at http://docs.cloudfoundry.org/deploying/ec2/cf-stub-aws.html is outdated. The included file is no longer in sync with https://raw.githubusercontent.com/cloudfoundry/cf-release/master/spec/fixtures/aws/cf-stub.yml which is probably should be.

**Comment by Amit-PivotalLabs** [comment]
@voelzmo that's an issue with the docs, not this repo.  I think of deploying CF on AWS as having 5 main steps:

1. Provision AWS
2. Create bosh-init manifest for BOSH
3. Deploy BOSH
4. Create stub for CF
5. Feed stub into manifest generation tool, and deploy CF

We are working towards building a toolchain for 1-3 called "mega-bootstrap".  An initial throwaway attempt at solving that problem is [here](https://github.com/cloudfoundry/mega-ci).  Based on learnings from that, we will be taking a second pass at that problem in the coming months.  This repo is primarily focused on 5, with the particular goal of supporting composition of multiple releases, *and* supporting the dev, test, and integration uses cases.

4 is very hard, and that is a longer term goal of MEGA.  We hope to achieve that by minimizing the need to do it at all, features such as BOSH cloud config and links will remove the need for much of it.  However, we are not solving that right now.

Right now, the best answer for 4 is the docs that you found, and the expectation that the power user will understand enough about BOSH to extend the example stub to do things like change the number of instances of things, for example.

As you noticed, the example stub you found on the docs website is out of date.  I am addressing that here: https://github.com/cloudfoundry/docs-deploying-cf/pull/67.

There are 4 main issues with the example stubs on the docs website, as I see them:

1. Making the example stubs realistic enough to be confident that someone following the docs will get a working deployment.
2. Automatically ensuring that those example stubs continue to provide a working deployment.
3. Making the explanation of how to fill out the stub on the docs website correct.
4. Automatically ensuring that those explanations remain correct as things change.

I have [this story](https://www.pivotaltracker.com/story/show/105805252) to address 1, by making the stubs roughly match up with the stubs we use in our real CI environments.  I have vague ideas about how to accomplish 2, but nothing concrete. I am addressing 3, at least for AWS, in the PR mentioned above, and I will do it for the other infrastructures as I make the stubs more realistic as well.  4, like 2, I don't have a great idea how to accomplish.

Hope this answers your questions, I will close this issue for now.

**Comment by voelzmo** [comment]
Thanks @Amit-PivotalLabs, I might have had too big expectations for this repo and its documentation. I'll try to move to a better solution for creating the cf stubs for us internally.

Maintaining the explanations at the same speed as the stubs change is just the general problem that every piece of documentation has: keeping it correct and up-to-date is a huge effort, especially if you're moving fast.

**Comment by Amit-PivotalLabs** [comment]
Yeah, typically the way people maintain stubs right now is they do the
arduous work to get it right one time, and then keeping up with changes is
not so difficult if you do it frequently. The cf-release Release Notes
should often help with this.
