### ISSUE TITLE
Error: Job 'nats_stream_forwarder' not found in Template table

### ISSUE THREAD

**Issue by mllives** [cloudfoundry/cf-deployment#733]
when I deploy CF on the openstack with bosh, it turned out to be :
Error: Job 'nats_stream_forwarder' not found in Template table.

The command I used was :  "bosh -e bosh/0 -d openstack-cf deploy cf-deployment.yml"
The version of stemcell is  "bosh-openstack-kvm-ubuntu-trusty-go_agent  3431.10";
The version of release is "cf    270";
The cf-deployment.yml I used got from  "https://github.com/zhongjun2/docs/blob/master/cloudfoundry/cf-deployment.yml"

I would appreciate it if you can give me some advice. Thanks in advance!

**Comment by cdutra** [comment]
Hi @mllives, this his isn't a cf-deployment manifest we maintain. You can find the [list of cf-deployment manifests we maintain here](https://github.com/cloudfoundry/cf-deployment/releases).

The manifest you linked seems to still be a bosh v1 manifest. This is deprecated

I'm closing the issue since doesn't seem related to cf-deployment.
