### ISSUE TITLE
default branch "develop" can be painful for consumers

### ISSUE THREAD

**Issue by robdimsdale** [cloudfoundry/cf-deployment#76]
As a consumer of cf-deployment who wants a functioning CF as a black box, I was confused to clone the repo and find the deploy broken because the default branch `develop` is not guaranteed to be stable.

The README does call out that `master` is the stable branch, but even knowing this it took me a long time to realize the repo I just cloned was on `develop`.

I understand the main driver for setting `develop` to be the default branch is to facilitate pull-requests, which generally should be made against `develop` not `master`. I know the frustration that can be caused by having to close PRs because they were made against the wrong branch.

I think that setting the default branch to `master` will provide a better experience for the consumers who want a CF without caring too much about contributing back, so the question becomes which use-case do we want to optimize for?

There's advantages and disadvantages to both choices. What do you think?

**Comment by dsabeti** [comment]
@robdimsdale I think you have a good point, that people expect to be able to clone a repo and start using it.

I think part of the issue is that we want different default branches for "consuming" and "producing" -- the former would be `master` and the latter would be `develop`. Unfortunately, there's no github feature for setting different defaults for `git clone` and PRs (or even more interesting, `git clone git@...` and `git clone https://...`)

Anyway, it probably makes the most sense to go with `master`, since more and more people are moving into the "consumer" category. I'll let @anEXPer chime in if he has an opinion.

**Comment by anEXPer** [comment]
I think we've probably reached the point in the life of this repo that we should switch it the default branch for consumers, rather than for contributors. We can message about making PRs from develop in the readme and potentially elsewhere.

Let's change the default branch to `master`.

**Comment by dsabeti** [comment]
I've changed the default to master.

**Comment by robdimsdale** [comment]
Excellent, thanks all.
