### ISSUE TITLE
Retrieving your CF admin password is not obvious

### ISSUE THREAD

**Issue by ljfranklin** [cloudfoundry/cf-deployment#80]
After you've set up your shiny new cf-deployment Cloud Foundry, you'll probably want to login with the `cf` CLI. Unless you're familiar the new BOSH CLI and the large variables section in cf-deployment, it is not obvious that you should run `bosh interpolate --path /uaa_scim_users_admin_password env-repo/deployment-vars.yml` to retrieve your CF admin password. An example in the README would be helpful, maybe renaming `uaa_scim_users_admin_password` to `cf_admin_password` or similar might also be nice.

**Comment by ljfranklin** [comment]
cc @thausler786

**Comment by dsabeti** [comment]
Hey @ljfranklin.

I think this is valuable feedback. For now, we can definitely add something to the README pretty easil. I'd also like for our team to explore renaming the variable so that it's named in a more meaningful way. The difficulty is that a bunch of deployers already have `uaa_scim_users_admin_password` in their vars stores, so we'd have to make it simple for them to "migrate" or alias those variables.

**Comment by ljfranklin** [comment]
Closing this out as `cf_admin_password` is a thing now. Thanks!

**Comment by cwlbraa** [comment]
if you found this issue but you're credhubbing without a local vars-store:
```credhub find -n cf_admin_password -j | jq '.credentials[0].name' | xargs -n1 credhub get -j -n | jq '.value' -r | xargs -n1 cf auth admin```
