### ISSUE TITLE
CATS errand missing

### ISSUE THREAD

**Issue by tscolari** [cloudfoundry/cf-deployment#82]
The cf-release has an acceptance-test errand that we currently use to make sure our team's changes don't break our test CF deployment. It'd be great if cf-deployment could also (optionally?) provide this errand. For now we're having to upload all of cf-release just to be able to add it back to our deployment.

**Comment by dsabeti** [comment]
Hi @tscolari.

Have you seen our [concourse task for running CATs](https://github.com/cloudfoundry/cats-concourse-task)? It's the way to run CATs that the Release Integration team is supporting. Would this meet your team's needs, or is there a reason that you need an errand specifically?

For context, one of the positions cf-deployment is taking is that CATs is for developer teams to validate their code changes -- not for deployers who want to validate their configuration. That's why we want to support a concourse task instead of a BOSH errand.

**Comment by tscolari** [comment]
Hello @dsabeti 

That should work for us.
It does require a bit more of setup (e.g. parsing credentials into the json file), but it will do for us :)
We atm are still pushing the cf-release and running the errand, but we've added a chore to migrate to the concourse task.

Many thanks!

**Comment by bingosummer** [comment]
Does it make sense to add an ops file to add a CATS errand?

**Comment by dsabeti** [comment]
@bingosummer, you could always write such an ops-file for yourself, but I probably wouldn't want to add it to cf-deployment. As I said, I see it as a test suite for the CF development teams, who primarily use Concourse.

However, I'd be interested to hear how you'd like to CATs -- are you using the test suite to validate changes to the releases themselves, or do you want to validate the functionality of a particular deployment? What tooling are you (Concourse, Travis, errands, etc.) are you currently using to run CATs?

**Comment by bingosummer** [comment]
Thanks @dsabeti .
To verify the PR #191 , I use https://github.com/cloudfoundry/cats-concourse-task to run CATs. But to provide credentials for integration-config, I have to make some [changes](https://github.com/bingosummer/cats-concourse-task/commit/62cc22085d5eff339024a51994b0de810da91ee3) to provide credentials directly instead of the integration-config repo.

Agreed with you. I can write ops-file by myself if someone in my team prefers the errand.
