### ISSUE TITLE
Track loggregator issue: syslog drains break with basic auth in cf-d 13.0-13.2

### ISSUE THREAD

**Issue by ericpromislow** [cloudfoundry/cf-deployment#883]
### What is this issue about?

Track [cloudfoundry/loggregator-agent-release #29](https://github.com/cloudfoundry/loggregator-agent-release/issues/29)

syslog drains break with basic auth

### What version of [cf-deployment](https://github.com/cloudfoundry/cf-deployment/releases) are you using?

13.0-13.2

Slack thread: https://cloudfoundry.slack.com/archives/C2U7KA7M4/p1590428109070300

In the thread Jesse estimates a fix will be out around June 3

**Comment by jamespollard8** [comment]
The fix to https://github.com/cloudfoundry/loggregator-agent-release/issues/29 was shipped in loggregator-agent v6.0.1

A couple additional bugs came up:
* https://github.com/cloudfoundry/loggregator-agent-release/issues/31 was fixed in v6.0.2
* https://github.com/cloudfoundry/loggregator-agent-release/issues/34 is currently open, has been considered non-critical for the vast majority of users, and the plan is to fix it in loggregator-agent v6.1.0.

In cf-d [release v13.5.0](https://github.com/cloudfoundry/cf-deployment/releases/tag/v13.5.0), we bumped from loggregator-agent v6.0.0 to v6.0.2
