### ISSUE TITLE
Logging VMs update order broken

### ISSUE THREAD

**Issue by jkbschmid** [cloudfoundry/cf-deployment#910]
### What is this issue about?

Update sequence of Doppler and Log API VMs leads to uneven load distribution for RLP instances, where the last RLP instance will likely not receive any traffic at all. 

In `cf-deployment.yaml`, Log API instances are listed after Doppler VMs. This leads to the following scenario when updating Doppler, RLP and Log Cache Nozzle processes: 
1. Doppler VMs are updated.
Log Cache Nozzles connect to RLPs. RLPs connect to Dopplers.

2. Log API VMs are updated.
Each restart causes all Log Cache Nozzles that are connected to this RLP instance to disconnect. 
The nozzles try to [establish a new connection](https://github.com/cloudfoundry/log-cache-release/blob/847aac3a0a2e04153965adf76d73ff64dfbdd2c5/src/internal/nozzle/nozzle.go#L100) to the RLP URL which is resolved via BOSH DNS to an available RLP instance.

Since Log API VMs are updated one after another (we are using max_in_flight=10%), for the last instance to be updated, this means:
All `n` previously connected Log Cache Nozzles are disconnected and try to reconnect to a RLP. Due to Round Robin load balancing, the chance of being resolved to the current RLP instance is `1/m`, where m is the number of Log APIs. In sum, the last RLP instance roughly has an expected number of incoming requests of  `n * 1/m`. 
Since the recommended number of Log API VMs is half the number of Doppler VMs, i.e. `n<m`, most of the time it won’t receive any connection at all.
This leads to situations, where some instances receive no traffic at all, whereas others are dropping logs due to being overloaded.

![image](https://user-images.githubusercontent.com/44965368/96464465-22fe1200-1228-11eb-9f70-641e35c4b3ff.png)

### What version of [cf-deployment](https://github.com/cloudfoundry/cf-deployment/releases) are you using?

[cf-deployment v13.20.0 here]

**Comment by acosta11** [comment]
Hi @jkbschmid,
Thanks for the issue! We appreciate the detail and thorough explanations provided! We went ahead and reached out to logging folks [in slack](https://cloudfoundry.slack.com/archives/CUW93AF3M/p1603127539054800).

The issue description seems to suggest we update the deployment order here, so we would be curious to know if you happen to have already tried to do so? Did making that change balance the connections/load across the LRP processes? As we don't have TPS metrics set up on our own CI environments, it would be more difficult for us to validate this issue. If the metrics look reasonable, we'd be happy to open and merge a PR with the suggested changes.

Given the parallelization of bosh deployments, we worry that the actual requirement here is a mitigation of the race between doppler update and log api update through adding a `serial: true` to enforce that ordering. But we're more wary of that kind of change to the manifest due to its affect on overall deployment speed.

Thanks,
Andrew and @davewalter

**Comment by jkbschmid** [comment]
Hi @acosta11 and @davewalter,
thanks for the quick response! I just tried the change on a small dev foundation and it did indeed balance the connections and load across the RLP processes. 
The connections are still distributed via DNS, so reordering the deployments leads to the probability of proper distribution being high. It's still possible to get uneven load distribution, especially when there are only few Dopplers. Even so, reordering would be a good improvement.
I also saw that traffic was unevenly spread across Dopplers (Doppler ingress), but I think this is an unrelated issue (https://github.com/cloudfoundry/loggregator-agent-release/issues/38).

I completely agree that we should try to avoid extending the deploy time even further. So if we would get proper load distribution by periodic client reconnects (as discussed in Slack) then I would also prefer that over serializing the deployments.

Thanks,
Jakob

**Comment by davewalter** [comment]
Hi @jkbschmid,

Thanks for the update. I'll leave it to our logging friends to comment on the solution that doesn't involve modifying the deployment.

Regards,
Dave

**Comment by jkbschmid** [comment]
Hi @pianohacker, @MasslessParticle,
as you are the loggregator experts, it would be awesome to have your thoughts on this issue:)

Do you think forcing reconnects would create too many message drops? To have a meaningful impact, I think we would need reset intervals < 1 hour so that sufficient rebalancing is done timely after an update.

@MasslessParticle, you mentioned some "cleverness" to decrease drops during restarts. Would this be a rather manageable implementation effort or do you think we should serialize the instance deployments until a fix is implemented in loggregator (clients)?

Thanks,
Jakob

**Comment by MasslessParticle** [comment]
@jkbschmid I think that reordering the deployments ought to be the first course of action. Particularly because both @pianohacker and myself have been shuffled off of the Bosh Log Egress team

With regard to the cleverness I mentioned: in the Syslog Agents, we handle this issue by spinning up a new connection before we tear down the old one. I think we'd need to do something along those lines. We've gotten feedback that any loss due to reconnects is unacceptable to some users. 

I'm looping in @Benjamintf1 @kkburr and @JSchuenke who are doing more ongoing work with the Bosh logging components.

**Comment by jkbschmid** [comment]
Hi all,
would you accept a PR with the mitigation to serialize Doppler and Log API VMs, as @MasslessParticle suggested, @davewalter, @acosta11 ?

The resulting deployment would look like so:
1. Log API VMs are updated.
Log Cache Nozzles have to reconnect, which temporarily causes the current imbalance on RLP instances.

2. Doppler VMs are updated.
Log Cache Nozzles connect to RLPs (this time connections are uniformly distributed). RLPs connect to Dopplers.

Thanks,
Jakob

**Comment by jamespollard8** [comment]
Sounds good to me @jkbschmid 👍

**Comment by chombium** [comment]
Thanks for the replay @jamespollard8 we'll prepare a PR.

**Comment by davewalter** [comment]
Hi @jkbschmid and @chombium,

I am going to close this issue out due to inactivity. We would still be open to a PR if you are able to create one.

Regards,
Dave
